spring.thymeleaf.cache=false
server.port=8182

# dev
#spring.datasource.url=jdbc:postgresql://localhost:5432/thi_hanh_an
#spring.datasource.username=huutk
#spring.datasource.password=123456
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true

#spring.datasource.url=jdbc:postgresql://ep-morning-rice-a1eo44sh-pooler.ap-southeast-1.aws.neon.tech:5432/thi_hanh_an?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_VPj1gdN0qRhH
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.url=jdbc:sqlite:excel2word.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
